version: "2.2"
services:
  web:
    build: ./.docker
    environment:
      - ADMIN_USER=moriarty
      - ADMIN_PASS=Pass@123
    ports:
      - 8080:80
    volumes:
      - ./src/ffserver:/code/ffserver
      - ./src/htdocs:/usr/share/nginx/html
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    mem_limit: 100M
